### ISSUE TITLE
DCGAN and CGAN suffer from mode collapse

### ISSUE THREAD

**Issue by kunwardeeps** [mafda/generative_adversarial_networks_101#3]
After training for 200 epochs with the CIFAR 10 dataset, I found that the DCGAN and CGAN generated images do not have enough variety. Most likely a mode collapse happening.

**Comment by mafda** [comment]
Regards,

Mode collapse is one of the main problems that occur during GANs training, which means that the generator produces limited varieties of samples. 

In recent work, researchers have presented some studies that suggest some methods to reduce the problem of mode collapse, such as:

* studies that explore new objective functions, like [Unrolled GAN](https://arxiv.org/abs/1611.02163) and [Deep Regret Analytic GAN (DRAGAN)](https://arxiv.org/abs/1705.07215),
* studies that propose architectural modifications like [Multiagent Diverse GAN (MAD-GAN)](https://arxiv.org/abs/1704.02906) and [Mode Regularized GAN (MRGAN)](https://arxiv.org/abs/1612.02136), and
* studies with mini-batch discrimination like [Progressive GAN](https://arxiv.org/abs/1710.10196).

For more information, these works are recommended:
* [NIPS 2016 Tutorial: Generative Adversarial Networks](https://arxiv.org/abs/1701.00160)
* [Generative Adversarial Networks: An Overview](https://arxiv.org/abs/1710.07035)
* [How Generative Adversarial Networks and Their Variants Work: An Overview](https://arxiv.org/abs/1711.05914)

Thanks
