### ISSUE TITLE
why we use discriminator.trainable = False before d_g.train_on_batch(x=z, y=real) in 01_GAN_MNIST_original?

### ISSUE THREAD

**Issue by GussailRaat** [mafda/generative_adversarial_networks_101#4]
for e in range(epochs):
        for i in range(len(X_train) // batch_size):

            # Train Discriminator weights
            discriminator.trainable = True

            # Real samples
            X_batch = X_train[i*batch_size:(i+1)*batch_size]
            d_loss_real = discriminator.train_on_batch(x=X_batch, y=real * (1 - smooth))

            # Fake Samples
            z = np.random.normal(loc=0, scale=1, size=(batch_size, latent_dim))
            X_fake = generator.predict_on_batch(z)
            d_loss_fake = discriminator.train_on_batch(x=X_fake, y=fake)

            # Discriminator loss
            d_loss_batch = 0.5 * (d_loss_real[0] + d_loss_fake[0])

            # Train Generator weights
            discriminator.trainable = False   <<============
            d_g_loss_batch = d_g.train_on_batch(x=z, y=real)

Hello, I know the process of GAN but I am a little bit confused with the use of **discriminator.trainable = False** (see <<============) because in d_g, the discriminator is already false so can we remove this from here (<<============) or it has some other meaning here and I am not able to get it? 

Please help me out. Thank you.

**Comment by mafda** [comment]
Hi,

Thank you for your feedback.

The model has to be set to false before it is compiled `cell [11]`.

And while training, the discriminator and generator have to alternate between true and false  `cell [14]`, in a loop as follows:

1. Set the discriminator trainable.
2. Train the discriminator with the real images and the images generated by the generator to classify the real and fake images (half the samples are real, and half are fake).
3. Set the discriminator non-trainable.
4. Train the generator as part of the GAN. We feed latent samples into the GAN and let the generator to produce images and use the discriminator to classify the image.


However, if I delete one of the lines of code `cel [11]` or `cel [14]`, I have the following warning:

`UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'`

So, I don't know if it’s safe to erase it from either cell.

Hope I could help.

**Comment by GussailRaat** [comment]
Thank you for the clarification.
